#' @title check_clustering
#'
#' @description Generates a FeaturePlot of scores generated by the Silhouette method. Use
#'     to evaluate how well the cells fit their assigned cluster.
#'
#' @param seurat_object A Seurat object
#' @param dims A sequence of numbers indicating the number of dimensions (default is 1:30)
#' @param cluster_col the metadata column indicating the clusters to assess (default is "harmony_clusters")
#' @param slot A dimensional reduction present in the Seurat object (default is "pca")
#'
#' @return a Seurat FeaturePlot of scores generated by the Silhouette method.
#'
#' @export
#'
check_clustering <- function(seurat_object, dims = 1:30, cluster_col = "harmony_clusters", slot = "pca") {

  #https://github.com/satijalab/seurat/issues/1985

  dist.matrix <- dist(x = Embeddings(object = seurat_object[[slot]])[, dims])
  clusters <- seurat_object[[cluster_col]]
  sil <- cluster::silhouette(x = as.numeric(x = as.factor(x = clusters)), dist = dist.matrix)
  seurat_object$sil <- sil[, 3]

  p1 <- FeaturePlot(seurat_object, "sil") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))

  return(p1)
}
